version: "3"

services:

  nginx:
    build: nginx
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default:/etc/nginx/sites-available/default
      - ./logs/:/var/log/nginx/
    ports:
      - "8013:80"
