version: "3"

services:

  # You can "tail /var/log/nginx/error.log -f"  for streaming logs
  nginx:
    build: nginx 
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default:/etc/nginx/sites-available/default
      - ./logs/:/var/log/nginx/
    ports:
      - "8013:80" # nchan