version: "3"

services:

  # You can "tail /var/log/nginx/error.log -f"  for streaming logs
  # nchan server
  nchan:
    build: nchan 
    container_name: nchan
    restart: unless-stopped
    volumes:
      - ./nchan/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nchan/conf/default:/etc/nginx/sites-available/default
      - ./nchan/logs/:/var/log/nginx/
    ports:
      - "8013:80" # nchan public ip
    networks:
      agent:
        ipv4_address: 172.25.0.101
      default:

  # reservation server
  reservation:
    build: node
    container_name: reservation
    volumes:
      - ..:/usr/src/service
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
      - nchan
      - rabbitmq
    working_dir: /usr/src/service
    command: node src/start.js API
    #command: tail -f /dev/null # For debugging if you comment the line above (to run server manually)
    networks:
      agent:
        ipv4_address: 172.25.0.100
      default:

  # mongodb
  mongo:
    container_name: mongo
    image: mongo
    expose:
      - 27017
    networks:
      agent:
        ipv4_address: 172.25.0.102

  # rabbitmq
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      agent:
        ipv4_address: 172.25.0.103

  # coin - bwk - Bulwark
  bwk:
    container_name: bwk
    build: coins/bwk
    ports:
      - "52543:52543"
    networks:
      agent:
        ipv4_address: 172.25.0.110

networks:
  agent:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24